# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  AudIo_config = debug

else ifeq ($(config),release)
  AudIo_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := AudIo

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

AudIo:
ifneq (,$(AudIo_config))
	@echo "==== Building AudIo ($(AudIo_config)) ===="
	@${MAKE} --no-print-directory -C . -f AudIo.make config=$(AudIo_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f AudIo.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   AudIo"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"